// Generated by CoffeeScript 1.6.3
(function() {
  window.Safarikai = (function() {
    var readDataFile;
    readDataFile = function(file) {
      var fileContent, req;
      req = new XMLHttpRequest();
      req.open("GET", safari.extension.baseURI + "data/" + file, false);
      req.send(null);
      return fileContent = req.responseText;
    };
    return {
      boot: function() {
        return console.log("Safarikai global script booted.");
      }
    };
  })();

}).call(this);
