// Generated by CoffeeScript 1.6.3
(function() {
  window.Safarikai = (function() {
    var messageEventHandler, readDataFile;
    readDataFile = function(file) {
      var fileContent, req;
      req = new XMLHttpRequest();
      req.open("GET", safari.extension.baseURI + "data/" + file, false);
      req.send(null);
      return fileContent = req.responseText;
    };
    messageEventHandler = function(e) {
      var messageData, messageName;
      messageName = e.name;
      messageData = e.message;
      return console.log(messageData);
    };
    return {
      boot: function() {
        safari.application.addEventListener("message", messageEventHandler, false);
        return console.log("Safarikai global script booted.");
      }
    };
  })();

}).call(this);
