// Generated by CoffeeScript 1.6.3
(function() {
  (function() {
    var lookupWord, messageEventHandler, queryWord, readDataFile, result;
    readDataFile = function(file) {
      var fileContent, req;
      req = new XMLHttpRequest();
      req.open("GET", safari.extension.baseURI + "data/" + file, false);
      req.send(null);
      return fileContent = req.responseText;
    };
    queryWord = "";
    result = "";
    lookupWord = function(word) {
      console.log("lookup word: " + word);
      if (queryWord !== word) {
        queryWord = word;
        result = queryWord;
      }
      return safari.application.activeBrowserWindow.activeTab.page.dispatchMessage("showResult", {
        word: queryWord,
        result: result
      });
    };
    messageEventHandler = function(e) {
      var messageData, messageName;
      messageName = e.name;
      messageData = e.message;
      switch (messageName) {
        case "lookupWord":
          return lookupWord(messageData);
      }
    };
    safari.application.addEventListener("message", messageEventHandler, false);
    return console.log("Safarikai global script booted.");
  })();

}).call(this);
