// Generated by CoffeeScript 1.6.3
(function() {
  (function(doc, window) {
    var messageEventHandler, mouseEventHandler;
    mouseEventHandler = function(e) {
      var range, sel;
      range = doc.caretRangeFromPoint(e.clientX, e.clientY);
      if (range) {
        range.expand("word");
        sel = doc.defaultView.getSelection();
        return safari.self.tab.dispatchMessage("testMessage", range.toString());
      }
    };
    doc.onmousemove = doc.onmouseover = doc.onmouseout = mouseEventHandler;
    messageEventHandler = function(e) {
      var messageData, messageName;
      messageName = e.name;
      return messageData = e.message;
    };
    return safari.self.addEventListener("message", messageEventHandler, false);
  })(document, window);

}).call(this);
