// Generated by CoffeeScript 1.6.3
(function() {
  (function(doc, window) {
    var mouseEventHandler;
    mouseEventHandler = function(e) {
      var range, sel;
      range = doc.caretRangeFromPoint(e.clientX, e.clientY);
      if (range) {
        range.expand("word");
        return sel = doc.defaultView.getSelection();
      }
    };
    return doc.onmousemove = doc.onmouseover = doc.onmouseout = mouseEventHandler;
  })(document, window);

}).call(this);
