//
//  Romaji.swift
//  Safarikai
//
//  Created by James Chen on 2016/12/05.
//  Copyright © 2016 ashchan.com. All rights reserved.
//

import Foundation
import Regex

// swiftlint:disable type_body_length
class Romaji {
    class func romaji(from katakana: String) -> String {
        var values = hiragana(from: katakana).map { return romaji[$0] ?? $0 }.joined()

        for transform in hepburn {
            values.replaceAll(matching: Regex(transform.first!), with: String(describing: transform.last!))
        }

        return values
    }

    class func hiragana(from katakana: String) -> [String] {
        return katakana.map { return kana[String($0)] ?? String($0) }
    }

    static let kana: [String: String] = [
        "ア": "あ",
        "ァ": "ぁ",
        "イ": "い",
        "ィ": "ぃ",
        "ウ": "う",
        "ゥ": "ぅ",
        "エ": "え",
        "ェ": "ぇ",
        "オ": "お",
        "ォ": "ぉ",
        "カ": "か",
        "ガ": "が",
        "キ": "き",
        "ギ": "ぎ",
        "ク": "く",
        "グ": "ぐ",
        "ケ": "け",
        "ゲ": "げ",
        "コ": "こ",
        "ゴ": "ご",
        "サ": "さ",
        "ザ": "ざ",
        "シ": "し",
        "ジ": "じ",
        "ス": "す",
        "ズ": "ず",
        "セ": "せ",
        "ゼ": "ぜ",
        "ソ": "そ",
        "ゾ": "ぞ",
        "タ": "た",
        "ダ": "だ",
        "チ": "ち",
        "ヂ": "ぢ",
        "ツ": "つ",
        "ヅ": "づ",
        "ッ": "っ",
        "テ": "て",
        "デ": "で",
        "ト": "と",
        "ド": "ど",
        "ナ": "な",
        "ニ": "に",
        "ヌ": "ぬ",
        "ネ": "ね",
        "ノ": "の",
        "ハ": "は",
        "バ": "ば",
        "パ": "ぱ",
        "ヒ": "ひ",
        "ビ": "び",
        "ピ": "ぴ",
        "フ": "ふ",
        "ブ": "ぶ",
        "プ": "ぷ",
        "ヘ": "へ",
        "ベ": "べ",
        "ペ": "ぺ",
        "ホ": "ほ",
        "ボ": "ぼ",
        "ポ": "ぽ",
        "マ": "ま",
        "ミ": "み",
        "ム": "む",
        "メ": "め",
        "モ": "も",
        "ラ": "ら",
        "リ": "り",
        "ル": "る",
        "レ": "れ",
        "ロ": "ろ",
        "ヤ": "や",
        "ャ": "ゃ",
        "ユ": "ゆ",
        "ュ": "ゅ",
        "ヨ": "よ",
        "ョ": "ょ",
        "ワ": "わ",
        "ヲ": "を",
        "ヰ": "ゐ",
        "ゑ": "ゑ",
        "ン": "ん"
    ]

    static let romaji: [String: String] = [
        "あ": "a",
        "ぁ": "xa",
        "い": "i",
        "ぃ": "xi",
        "う": "u",
        "ぅ": "xu",
        "え": "e",
        "ぇ": "xe",
        "お": "o",
        "ぉ": "xo",
        "か": "ka",
        "が": "ga",
        "き": "ki",
        "ぎ": "gi",
        "く": "ku",
        "ぐ": "gu",
        "け": "ke",
        "げ": "ge",
        "こ": "ko",
        "ご": "go",
        "さ": "sa",
        "ざ": "za",
        "し": "si",
        "じ": "zi",
        "す": "su",
        "ず": "zu",
        "せ": "se",
        "ぜ": "ze",
        "そ": "so",
        "ぞ": "zo",
        "た": "ta",
        "だ": "da",
        "ち": "ti",
        "ぢ": "di",
        "つ": "tu",
        "づ": "du",
        "っ": "xtu",
        "て": "te",
        "で": "de",
        "と": "to",
        "ど": "do",
        "な": "na",
        "に": "ni",
        "ぬ": "nu",
        "ね": "ne",
        "の": "no",
        "は": "ha",
        "ば": "ba",
        "ぱ": "pa",
        "ひ": "hi",
        "び": "bi",
        "ぴ": "pi",
        "ふ": "fu",
        "ぶ": "bu",
        "ぷ": "pu",
        "へ": "he",
        "べ": "be",
        "ぺ": "pe",
        "ほ": "ho",
        "ぼ": "bo",
        "ぽ": "po",
        "ま": "ma",
        "み": "mi",
        "む": "mu",
        "め": "me",
        "も": "mo",
        "ら": "ra",
        "り": "ri",
        "る": "ru",
        "れ": "re",
        "ろ": "ro",
        "や": "ya",
        "ゃ": "xya",
        "ゆ": "yu",
        "ゅ": "xyu",
        "よ": "yo",
        "ょ": "xyo",
        "わ": "wa",
        "を": "wo",
        "ゐ": "wi",
        "ゑ": "we",
        "ん": "n'",
        "ー": "-"
    ]

    static let hepburn: [[StaticString]] = [
        ["n\\'([^aiueoy]|$)", "n$1"],
        ["ixy", "y"],
        ["z(?:(i)|y)", "j$1"],
        ["xtu([a-z])", "$1$1"],
        ["s(?:(i)|y)", "sh$1"],
        ["t(?:(i)|y)", "ch$1"],
        ["tu", "tsu"],
        ["d(?:(i)|y)", "j$1"],
        ["du", "zu"],
        ["o[ou\\-]", "ō"],
        ["u[u\\-]", "ū"],
        ["a[a\\-]", "ā"],
        ["e[e\\-]", "ē"],
        ["i\\-", "ī"],
        ["w([ie])", "$1"]
    ]
}
